version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      github:
        key: ${{secrets.GPR_KEY}}
        username: Shotrush
