package com.minecraftcivilizations.specialization.Combat;


import lombok.Getter;

/**
 * Tranient armor stats that are generated by a Blackmith
 * @author Alectriciti
 */
public class ArmorStatsCustom{

    @Getter
    double weight;
    @Getter
    double knockback_resist;
    public ArmorStatsCustom(double weight, double knockback_resist){
        this.weight = weight;
        this.knockback_resist = knockback_resist;
    }


    public static ArmorStatsCustom normal(){
        return new ArmorStatsCustom(-1, 0);
    }

}